
title:  Maybe Life is Not for Everyone by Poisonblack  # your title
url: 'http://www.3fan.com'
baseurl: '/online-cv' #change it according to your repository name



# Profile information
yourname: good  ## put your name
location: beijign.china


## Social Profiles
facebook: http://www.facebook.com/goodeminem  ## your facebook account url
twitter: http://www.twitter.com/godoeminem  ## your twitter account url
weibo: http://www.weibo.com/goodemi  ## your weibo account url
wechat: goodeminem616  ## you wechat num
mail:21834288@qq.com  ## your email 



# Update all the sections by editing the files inside _includes folder.
